### ISSUE TITLE
Error when creating token file

### ISSUE THREAD

**Issue by teHwHoly** [BlueAndi/niu-cloud-cli#9]
Hi there,

is there a known problem with the communication protocol?
Main branch gave me some protocol errors, so I tried the development branch as it was more recent.
When I want to create the token file, I get the following error:

```
Internal error.
file:///home/openhabian/niu-cloud-cli-dev/src/createToken.js:100
        yargs().exit(errorCode.FAILED);
        ^

ReferenceError: yargs is not defined
    at file:///home/openhabian/niu-cloud-cli-dev/src/createToken.js:100:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.19.0
```

**Comment by BlueAndi** [comment]
Hi,  the development branch should work. I am waiting in #8 to get feedback about it. But it looks like something is not working. Let me check it again on my side.

**Comment by BlueAndi** [comment]
I fixed it in the development branch. Unfortunately I have no account anymore to test it, because my time for free usage is over.

**Comment by teHwHoly** [comment]
Yes it's a shame that they started the payed access. I cloned the branch again and now I get just the following feedback:
`"Internal error."`

**Comment by teHwHoly** [comment]
I added my credentials in the niu-cloud-connector library and ran the test:
```
Creating session token ...
Error:
connect ECONNREFUSED 0.0.0.0:443
```

**Comment by teHwHoly** [comment]
My guess is that we have changes in the protocol as mentioned here:
[https://github.com/marcelwestrahome/home-assistant-niu-component/issues/31](https://github.com/marcelwestrahome/home-assistant-niu-component/issues/31)

**Comment by BlueAndi** [comment]
Yes, it looks like. I will have a look what they did in the ha component and see whether I can update accordingly. Let's see whether I can download the current niu app and disassemble it too.

**Comment by BlueAndi** [comment]
Everything should work now again. The problem was that v2 of the authentication API support stopped. Now I am using the v3 of the authentication API.

Please try again and don't forget to update the submodule too. If successful, I will merge it to the master branch and release a new version.

I plan an update to nodejs v20.x.x LTS later (my stupid virtual machine don't like the latest debian at the moment). Currently I am using v18.13.0

**Comment by teHwHoly** [comment]
I'm still getting the feedback "internal error."
Maybe I can find some time in between to alter the api to NIU.
Don't you think we need the other parameters, used eg. here?:
[https://github.com/marcelwestrahome/home-assistant-niu-component/blob/master/custom_components/niu/api.py](https://github.com/marcelwestrahome/home-assistant-niu-component/blob/master/custom_components/niu/api.py)

grant_type, scope and app_id are missing.

**Comment by teHwHoly** [comment]
I tried to include the mentioned parameters and also to switch over to md5-hex, but that didn't help so far.

**Comment by BlueAndi** [comment]
Sounds like you didn't update the git submodule. I verified with an account and everything was working. .md5 hash is already considered.

**Comment by teHwHoly** [comment]
Do you have any recommendation how to do that?
I used following command to get the ressources:
`git clone -b development --recursive https://github.com/BlueAndi/niu-cloud-cli.git niu-cloud-cli`
Now I also updated the submodule with:
`git clone -b development --recursive https://github.com/BlueAndi/niu-cloud-connector.git niu-cloud-connector`
inside the libs folder.
But I still get the internal error message.

**Comment by BlueAndi** [comment]
Can you go inside ./libs/niu-cloud-connector and check there the last log?
And did you after updating an "npm install" again?

**Comment by teHwHoly** [comment]
I searched for the log file but wasn't able to find it.
Yes I repeated `npm install` every time I change dependencies or update the library.

Strangely I still get this error, when running the test of the interface lib:
```
Error:
connect ECONNREFUSED 0.0.0.0:443
```
Is it because the domain can't be resolved to an IP?

**Comment by BlueAndi** [comment]
> Is it because the domain can't be resolved to an IP?

Hmm ... looks like. Are you in a docker container or something like that?

BTW can you remove the whole local repository on your hard disk and clone again the master branch?

Use the following commands to clone, install and create a token. I am interesting whether you still get the connection refused.
```
git clone --recursive https://github.com/BlueAndi/niu-cloud-cli
cd niu-cloud-cli
npm install

node niu-cloud-cli.js create_token <your-email-address> <your-password>
```

**Comment by teHwHoly** [comment]
That just gave me the hint I needed.
As DNS wasn't able to resolve the IP I installed and ran dnstracer and accessed the page.
The traffic ran over some filtering algorithms and it was by any reason blocked from resolving the corresponding IP. When routed directly to the dns server I have now success, using the new v3 api with the library.
Many thanks for your support and the great work you did!
